pipeline {
    agent any

    parameters {
        extendedChoice(
            name: 'BOARD',
            type: 'PT_CHECKBOX',
            groovyScript: '''
                def boards = ['all']
                try {
                    def url = new URL("https://raw.githubusercontent.com/MurtazaJ2/Peripheral_testing/bsp_vaidation_multi-board_support/boards.yaml")
                    def content = url.text
                    def matcher = content =~ /(?m)^([a-zA-Z0-9_-]+):/
                    matcher.each { match -> boards.add(match[1]) }
                } catch (Exception e) {}
                return boards.unique().join(',')
            ''',
            defaultValue: 'all',
            multiSelectDelimiter: ' ',
            description: 'Select board(s) to test. Options are loaded dynamically from boards.yaml.'
        )
        extendedChoice(
            name: 'TEST_SUITE',
            type: 'PT_SINGLE_SELECT',
            groovyScript: '''
                def tests = ['all']
                try {
                    def url = new URL("https://api.github.com/repos/MurtazaJ2/Peripheral_testing/contents/tests?ref=bsp_vaidation_multi-board_support")
                    def json = new groovy.json.JsonSlurper().parseText(url.text)
                    json.each { file ->
                        if (file.name.startsWith('test_') && file.name.endsWith('.py')) {
                            tests.add(file.name)
                        }
                    }
                } catch (Exception e) {}
                return tests.join(',')
            ''',
            defaultValue: 'all',
            description: 'Select a specific test suite to run, or "all" to run everything.'
        )
        string(name: 'MODEL_NAME', defaultValue: 'google/gemma-4-26b-a4b-it:free', description: 'The LLM model to use for RCA and discovery.')
    }

    environment {
        // Inject OpenRouter API key securely from Jenkins Credentials
        OPENROUTER_API_KEY = credentials('OPENROUTER_API_KEY')
    }

    stages {
        stage('Setup Environment') {
            steps {
                sh '''
                    # Move old artifacts to a history folder so they aren't re-archived, but are kept in the workspace
                    mkdir -p workspace_history/logs
                    mv .report*.json workspace_history/ 2>/dev/null || true
                    mv bsp_rca_report*.md workspace_history/ 2>/dev/null || true
                    mv logs/* workspace_history/logs/ 2>/dev/null || true
                    
                    # Create and activate virtual environment
                    python3 -m venv venv
                    . venv/bin/activate
                    
                    # Install testing dependencies
                    pip install -r requirements.txt
                    
                    # Install AI Agent dependencies
                    pip install -r agent_requirements.txt
                '''
            }
        }
        
        stage('Execute Tests') {
            steps {
                // We use catchError to ensure the pipeline continues to the post block even if tests fail,
                // so that we can capture the .report.json and bsp_rca_report.md files.
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    sh '''
                        . venv/bin/activate
                        
                        # Handle 'all' test suite selection
                        TEST_ARG="${TEST_SUITE}"
                        if [ "$TEST_ARG" = "all" ]; then
                            TEST_ARG="tests/"
                        else
                            TEST_ARG="tests/${TEST_ARG}"
                        fi
                        
                        # Run the BSP hardware validation tests
                        pytest ${TEST_ARG} --board ${BOARD} --json-report
                    '''
                }
            }
        }
    }

    post {
        always {
            // Archive the JSON report
            archiveArtifacts artifacts: '.report*.json', allowEmptyArchive: true
            
            // Archive the Root Cause Analysis report generated by the autonomous agent
            archiveArtifacts artifacts: 'bsp_rca_report*.md', allowEmptyArchive: true
            
            // Archive all test run logs
            archiveArtifacts artifacts: 'logs/*.log', allowEmptyArchive: true
        }
    }
}
